### ISSUE TITLE
Connection stays open if the daemon rejects during the setup phase

### ISSUE THREAD

**Issue by nsgundy** [Stream-Technologies/spread-for-node#5]
v. 1.1.1
If the daemon rejects a connection attempt during the setup phase (i.e. Auth exchange, etc.), the client emits an error event, but never disconnects from the daemon. Since there will then be no 'close' event and disconnect() hasn't been implemented, there doesn't seem a solid way for anyone using this package to attempt to reconnect.

Will send a PR shortly.

**Comment by PeteFromGlasgow** [comment]
Thanks for the contribution, we've merged it in.
